---
title: "methods"
author: "Pascale Goertler"
date: '2022-06-24'
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Methods

## Full text

```{r cars}
library(dplyr)

knitr::opts_knit$set(root.dir = '../') 
full_text_review <- read.csv('../data_clean/full_text_review_results.csv')

summary(full_text_review)

unique(full_text_review$include_exclude)

length(na.omit(full_text_review$ID)) #115 articles were reviewed as full text (107 from abstract review + 3 additions from updated search (R2) + 5 after qc)
```

# Results

```{r pressure, echo=FALSE}
results <- full_text_review[,c(2,44,45,49)]

results_summary <- results %>%
  group_by(include_exclude) %>%
  summarize(n())

results_summary

```

# QC

```{r}
exclude <- subset(results, include_exclude == "exclude" | include_exclude == "N") # 17

unique(exclude$include_exclude_reason) # should be (a) not original research, (b)not aquatic or marine, (c) connectivity not on the landscape (cellular, population, etc.)

# check
pro_48 <- subset(full_text_review, ID == "pro_48")
chl_14 <- subset(full_text_review, ID == "chl_14")
pro_42 <- subset(full_text_review, ID == "pro_42")
chl_13 <- subset(full_text_review, ID == "chl_13")
chl_70 <- subset(full_text_review, ID == "chl_70")
pro_5 <- subset(full_text_review, ID == "pro_5")

# qc decisions 
exclude$qc <- c("include", "a", "a", "a", "b", "a", "a", "a", "c", "a", "include", "a", "a", "a", "include", "include", "include")

exclude_summary <- exclude %>%
  group_by(qc) %>%
  summarize(n())

exclude_summary
```
# Final for analysis 

```{r}
full_text <- subset(full_text_review, include_exclude != "exclude" & include_exclude != "N")

analysis_dat <- rbind(full_text, pro_48, pro_42, chl_13, chl_70, pro_5) #98 total articles for analysis

write.csv(analysis_dat, "data_clean/analysis_dat.csv", row.names = FALSE)
```

## Abstract review

```{r}
abs <- read.csv("../data_clean/abstract_results_all.csv")
head(abs)

R2 <- read.csv("../data_raw/MB_abstract_review_Round2.csv")

# last search

mb_r3 <- read.csv("data_raw/additions_ab_review_MB_results.csv")
pg_r3 <- read.csv("data_raw/additions_ab_review_PG_results.csv")

a <- colnames(abs) 
b <- colnames(R2)
colnames(mb_r3) <- tolower(colnames(mb_r3))
c <- colnames(mb_r3)
colnames(pg_r3) <- tolower(colnames(pg_r3))
d <- colnames(pg_r3)

setdiff(a, d)
setdiff(d, a)

R2$reason <- "NA"

colnames(mb_r3)[3] <- "ID"
colnames(mb_r3)[7] <- "pub_year"
mb_r3$consistency_check <- "NA"

mb_r3$original_research_y_n <- ifelse(is.na(mb_r3$original_research_y_n), "n", mb_r3$original_research_y_n)

colnames(pg_r3)[2] <- "ID"
colnames(pg_r3)[6] <- "pub_year"
pg_r3$consistency_check <- "NA"

abs <- rbind(abs[,-c(1,5,7:9)], R2[,-c(5,7:9)], mb_r3[,-c(1,4,8,9)], pg_r3[,-c(3,7,8)])

length(unique(abs$ID)) # 191 abstracts reviewed

write.csv(abs, "data_clean/annotated_bibliography.csv")
```

# Results
```{r}
unique(abs$inclusion)
abs_exclude <- subset(abs, inclusion == "N" | inclusion == "n" | inclusion == "unsure" | inclusion == "no" | inclusion == "exclude" | inclusion == "n ") # not straight forward because of consistency check (e.g., have more results than articles)

IDs4exclude <- unique(abs_exclude$ID) #69 (but two are added back in bc of 25% consistency check disagreement)

# check against full text review results
a <- unique(analysis_dat$ID)
b <- unique(abs$ID)
setdiff(a, b)
length(setdiff(b, a)) # 65
length(setdiff(a, IDs4exclude)) # 95

abs_qc <- abs %>% 
  filter(ID %in% IDs4exclude)

abs_results <- abs_qc[,c(7:15)]

```

# QC

```{r}
unique(abs_results$reason)
length(is.na(abs_results$reason)) # 86

unique(abs_results$original_research_y_n)

abs_results$qc <- ifelse(abs_results$original_research_y_n == "meta-analysis" | 
                           abs_results$original_research_y_n == "N" |
                           abs_results$original_research_y_n == "n (review)" |
                           abs_results$original_research_y_n == "n", "a", NA)

abs_original_research <- subset(abs_results, qc == "a") #23

IDs_original_research <- unique(abs_original_research$ID) # 19 (4 duplicates)

# rewrite to filter when disagreements occur 
abs_original_research <- abs_results %>% 
  filter(ID %in% IDs_original_research) # added two (25)

# chl_70 <-- was reviewed in full text stage
# pro_3 <-- both say exclude, but have different reasons

abs_subset <- abs_results %>% 
  filter(!ID %in% IDs_original_research)

unique(abs_subset$marine_y_n)

abs_subset$qc <- ifelse(abs_subset$marine_y_n == "Y" | 
                           abs_subset$marine_y_n == "y", "b", NA)

abs_marine <- subset(abs_subset, qc == "b")
IDs_marine <- unique(abs_marine$ID) #  16 (no duplicates)

# rewrite to filter when disagreements occur 
abs_marine <- abs_subset %>% 
  filter(ID %in% IDs_marine) # added two

# chl_16 is a disagreement about inclusion and marine <-- was reviewed in full text stage
# pro_53 are in agreement on marine and exclude, just different notation 

abs_conn <- abs_subset %>% 
  filter(!ID %in% IDs_marine)

length(unique(abs_conn$ID)) # 34
unique(abs_conn$connectivity_metric)

ID <- c("chl_10", "chl_12", "chl_15", "chl_26", "chl_28", "chl_29", "chl_39", "chl_46", "chl_5", "chl_52", "chl_59", "chl_72", "chl_76", "pro_10", "pro_12", "pro_12", "pro_13", "pro_13", "pro_19", "pro_23", "pro_29", "pro_30", "pro_30", "pro_39", "pro_4", "pro_50", "pro_50", "pro_58", "pro_58", "pro_6", "pro_60", "pro_61", "pro_61", "pro_64", "pro_64", "pro_69", "pro_69", "pro_70", "pro_74", "pro_77", "pro_77", "r3_07", "r3_09")

qc <- c("include", "a", "a", "b", "c", "a", "b", "c", "include", "c", "b", "a", "c", "b", "b", "b", "a", "a", "b", "c", "b", "b", "b", "b", "include", "include", "include", "b", "b", "include", "a", "b", "b", "b", "b", "include", "include", "b", "include", "b", "b", "b", "c")

fin_abs <- data.frame(ID, qc)

# a will also include not written in English
# b will also include not aquatic

chl_10 <- subset(abs, ID == "chl_10") # water body type is river, "hyporheic flow" not a valid exclusion reason 
chl_26 <- subset(abs, ID == "chl_26") # missing primary review (only have Lauren's consistency check...)
chl_46 <- subset(abs, ID == "chl_46") # missing primary review
chl_5 <- subset(abs, ID == "chl_5") # water body type is reservoir, no mention of connectivity, but on the landscape, aquatic and original research
pro_10 <- subset(abs, ID == "pro_10")
pro_13 <- subset(abs, ID == "pro_13")
pro_4 <- subset(abs, ID == "pro_4")
pro_50 <- subset(abs, ID == "pro_50") # disagreement between reviewers on inclusion
pro_6 <- subset(abs, ID == "pro_6")
# pro_60 disagreement between reviewers on inclusion <-- was reviewed in full text stage
pro_74 <- subset(abs, ID == "pro_74")

# complete check
abs_original_research[5:6,10] <- "include" # chl_70
abs_original_research[10,10] <- "a" # pro_3

abs_marine[2:3,10] <- "include" # chl_16
abs_marine[8,10] <- "b" # pro_53

fin_abs <- rbind(fin_abs, abs_marine[,c(8,10)], abs_original_research[,c(8,10)])

length(unique(fin_abs$ID)) #69

check <- unique(fin_abs$ID)
setdiff(IDs4exclude, check) #

abs_summary <- fin_abs %>%
  group_by(qc) %>%
  summarise(count = n_distinct(ID))

abs_summary

```
# Final for analysis 

```{r}
head(fin_abs)
fin_ID <- unique(fin_abs$ID)

fin_abs_qc <- abs %>% 
  filter(!ID %in% fin_ID)

length(unique(fin_abs_qc$ID)) # 122 (add 9 from qc, total = 131)

# 191 abstracts reviewed, 232 reviews total bc of consistency check

fin_abs_qc$qc <- "include"

fin_abs <- rbind(fin_abs, fin_abs_qc[,c(14,16)])

write.csv(fin_abs, "data_clean/abstract_qc.csv", row.names = FALSE)


# bring in full text results

fin_abs$stage <- "abstract_review"

head(exclude)
exclude_ID <- unique(exclude$ID)

full_text_include <- full_text_review %>% 
  filter(!ID %in% exclude_ID)

full_text_include$qc <- "include"

full_text_fin <- rbind(exclude[,c(1,5)], full_text_include[,c(2,50)])
full_text_fin <- na.omit(full_text_fin)

full_text_fin %>%
  group_by(qc) %>%
  summarise(count = n_distinct(ID))

full_text_fin$stage <- "full_text_review"

write.csv(full_text_fin, "data_clean/full_text_qc.csv", row.names = FALSE)

qc_results <- rbind(unique(fin_abs), unique(full_text_fin))

qc_results %>%
  group_by(qc, stage) %>%
  summarise(count = n_distinct(ID))

# check that all abstract review = include, have a full text review result
abs_include <- subset(fin_abs, qc == "include")

a <- unique(abs_include$ID) # 163, excluded --> 16 - a, 28 - b 5 - c
b <- unique(full_text_fin$ID) #110 (it is going to be 114) excluded --> 10 - a, 1 - b 1 - c
c <- unique(analysis_dat$ID) # 98 (TBD)
needed <- setdiff(a, b)

# "chl_10" "chl_5"  "pro_4"  "pro_6"  "pro_74" need full text reviews

full_text_needed <- abs %>% 
  filter(ID %in% needed)

write.csv(full_text_needed, "data_clean/full_text_needed.csv", row.names = FALSE)
```
## After QC of full texts
```{r}
dat4ft <- read.csv("data_clean/full_text_qc.csv")

# after looking at full text, pro_6 is a review

ID <- c("chl_10", "chl_5",  "pro_4",  "pro_6",  "pro_74")
qc <- c("include", "include","include", "a","include")
stage <- "full_text_review"

ft_needed <- data.frame(ID, qc, stage)

dat4ft <- rbind(dat4ft, ft_needed)

dat4ft %>%
  group_by(qc) %>%
  summarise(count = n_distinct(ID))

write.csv(dat4ft, "data_clean/full_text_qc.csv", row.names = FALSE)# updated

ft <- unique(dat4ft$ID)
abs <- unique(fin_abs$ID)
setdiff(abs, ft)

a_check <- subset(fin_abs, qc == "a")
b_check <- subset(fin_abs, qc == "b")
c_check <- subset(fin_abs, qc == "c")

length(unique(a_check$ID))
length(unique(b_check$ID))
length(unique(c_check$ID))

a <- unique(a_check$ID)
b <- unique(b_check$ID)
c <- unique(c_check$ID)

intersect(a, include)

include_check <- subset(fin_abs, qc == "include")
length(unique(include_check$ID))
include <- unique(include_check$ID)

```

